#!/usr/bin/env python3
"""
Run Agent Script
Full workflow script that clones GitHub repositories and performs analysis.
Use this for complete repository analysis tasks.
"""

import os
import sys
import subprocess
import shutil
import time
import json
from pathlib import Path
from datetime import datetime

from planner_agent import create_planner_agent


def clone_repository(repo_url: str, target_dir: str = "./temp") -> str:
    """
    Clone a GitHub repository to a local directory.

    Args:
        repo_url: GitHub repository URL
        target_dir: Directory to clone repositories into

    Returns:
        Path to the cloned repository
    """
    print(f"\n[CLONE] Cloning repository: {repo_url}")

    # Create target directory if it doesn't exist
    Path(target_dir).mkdir(parents=True, exist_ok=True)

    # Extract repo name from URL
    repo_name = repo_url.rstrip('/').split('/')[-1].replace('.git', '')
    clone_path = os.path.join(target_dir, repo_name)

    # Remove existing clone if it exists
    if os.path.exists(clone_path):
        print(f"[WARNING] Repository already exists at {clone_path}")
        response = input("Remove and re-clone? (y/N): ").strip().lower()
        if response == 'y':
            print(f"[DELETE] Removing existing repository...")
            shutil.rmtree(clone_path)
        else:
            print(f"[OK] Using existing repository at {clone_path}")
            return clone_path

    # Clone the repository
    try:
        print(f"[CLONING] Cloning to {clone_path}...")
        result = subprocess.run(
            ["git", "clone", repo_url, clone_path],
            capture_output=True,
            text=True,
            check=True
        )
        print(f"[SUCCESS] Repository cloned successfully!")
        return clone_path

    except subprocess.CalledProcessError as e:
        print(f"[ERROR] Error cloning repository: {e.stderr}")
        sys.exit(1)


def save_analysis_reports(
    repo_name: str,
    repo_url: str,
    repo_path: str,
    final_instructions: str,
    tool_usage: dict,
    total_tokens: dict,
    duration_seconds: float,
    callback_handler
):
    """
    Save all analysis reports, metrics, and performance data to a structured folder.
    
    Args:
        repo_name: Name of the repository
        repo_url: URL of the repository
        repo_path: Path to the cloned repository
        final_instructions: Final build instructions
        tool_usage: Dictionary of tool usage statistics
        total_tokens: Dictionary of token usage
        duration_seconds: Analysis duration in seconds
        callback_handler: Callback handler with token usage
    """
    # Create analysis_reports directory in the root (parent of cra-planner-agent)
    # Get the directory where this script is located, then go up one level
    script_dir = Path(__file__).parent
    root_dir = script_dir.parent
    reports_base_dir = root_dir / "analysis_reports"
    reports_base_dir.mkdir(exist_ok=True)
    
    # Create timestamp for this analysis run
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_dir = reports_base_dir / f"{repo_name}_{timestamp}"
    report_dir.mkdir(exist_ok=True)
    
    print(f"\n{'='*70}")
    print("Saving Analysis Reports")
    print('='*70)
    print(f"Report directory: {report_dir.absolute()}")
    
    # 1. Save build instructions
    if final_instructions:
        build_instructions_file = report_dir / "BUILD_INSTRUCTIONS.md"
        try:
            with open(build_instructions_file, 'w', encoding='utf-8') as f:
                f.write(f"# Build Instructions: {repo_name}\n\n")
                f.write(f"*Generated by Planner Agent*\n\n")
                f.write(f"**Repository:** {repo_url}\n")
                f.write(f"**Analysis Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
                f.write("---\n\n")
                f.write(final_instructions)
            print(f"[OK] Build instructions saved: {build_instructions_file.name}")
        except Exception as e:
            print(f"[ERROR] Failed to save build instructions: {e}")
    
    # 2. Collect all metrics
    metrics = {
        "repository": {
            "name": repo_name,
            "url": repo_url,
            "local_path": str(repo_path)
        },
        "analysis": {
            "timestamp": timestamp,
            "date": datetime.now().isoformat(),
            "duration_seconds": duration_seconds,
            "duration_minutes": duration_seconds / 60,
            "duration_formatted": f"{int(duration_seconds // 60)} min {int(duration_seconds % 60)} sec" if duration_seconds >= 60 else f"{duration_seconds:.2f} seconds"
        },
        "token_usage": {},
        "tool_usage": {}
    }
    
    # Get token usage from callback handler or fallback
    if callback_handler and callback_handler.token_usage["total"] > 0:
        metrics["token_usage"] = callback_handler.token_usage.copy()
    elif total_tokens["total"] > 0:
        metrics["token_usage"] = total_tokens.copy()
    
    # Add tool usage statistics
    if tool_usage:
        total_tool_calls = sum(tool_usage.values())
        metrics["tool_usage"] = {
            "tools": {tool: {"calls": count, "percentage": (count / total_tool_calls * 100) if total_tool_calls > 0 else 0} 
                     for tool, count in sorted(tool_usage.items(), key=lambda x: x[1], reverse=True)},
            "total_calls": total_tool_calls,
            "unique_tools": len(tool_usage)
        }
    
    # 3. Save comprehensive performance report as JSON (includes everything)
    performance_json_file = report_dir / "performance_report.json"
    try:
        with open(performance_json_file, 'w', encoding='utf-8') as f:
            json.dump(metrics, f, indent=2, ensure_ascii=False)
        print(f"[OK] Performance report (JSON) saved: {performance_json_file.name}")
    except Exception as e:
        print(f"[ERROR] Failed to save performance report (JSON): {e}")
    
    # 4. Save human-readable performance report
    performance_txt_file = report_dir / "performance_report.txt"
    try:
        with open(performance_txt_file, 'w', encoding='utf-8') as f:
            f.write("="*70 + "\n")
            f.write("ANALYSIS PERFORMANCE REPORT\n")
            f.write("="*70 + "\n\n")
            
            f.write("Repository Information\n")
            f.write("-"*70 + "\n")
            f.write(f"Name: {repo_name}\n")
            f.write(f"URL: {repo_url}\n")
            f.write(f"Local Path: {repo_path}\n")
            f.write(f"Analysis Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            
            f.write("Analysis Duration\n")
            f.write("-"*70 + "\n")
            if duration_seconds >= 60:
                f.write(f"Total time: {int(duration_seconds // 60)} min {int(duration_seconds % 60)} sec ({duration_seconds:.2f} seconds)\n")
            else:
                f.write(f"Total time: {duration_seconds:.2f} seconds\n")
            f.write("\n")
            
            f.write("Token Usage Summary\n")
            f.write("-"*70 + "\n")
            if metrics["token_usage"]:
                usage = metrics["token_usage"]
                f.write(f"Input tokens:  {usage.get('input', 0):,}\n")
                f.write(f"Output tokens: {usage.get('output', 0):,}\n")
                f.write(f"Total tokens:  {usage.get('total', 0):,}\n")
            else:
                f.write("Token usage information not available\n")
            f.write("\n")
            
            f.write("Tool Usage Report\n")
            f.write("-"*70 + "\n")
            if metrics["tool_usage"] and metrics["tool_usage"].get("tools"):
                for tool_name, tool_data in metrics["tool_usage"]["tools"].items():
                    count = tool_data["calls"]
                    percentage = tool_data["percentage"]
                    f.write(f"{tool_name:30s} : {count:3d} calls ({percentage:5.1f}%)\n")
                f.write("-"*70 + "\n")
                f.write(f"{'Total tool calls':30s} : {metrics['tool_usage']['total_calls']:3d}\n")
                f.write(f"{'Unique tools used':30s} : {metrics['tool_usage']['unique_tools']:3d}\n")
            else:
                f.write("Tool usage information not available\n")
            f.write("\n")
            
            f.write("="*70 + "\n")
        print(f"[OK] Performance report (TXT) saved: {performance_txt_file.name}")
    except Exception as e:
        print(f"[ERROR] Failed to save performance report (TXT): {e}")
    
    print('='*70)
    print(f"\n[SUCCESS] All reports saved to: {report_dir.absolute()}")
    print('='*70)
    
    return report_dir


def analyze_repository(agent, repo_path: str, repo_name: str, repo_url: str, callback_handler):
    """
    Run analysis queries on a cloned repository.

    Args:
        agent: The planner agent instance
        repo_path: Path to the cloned repository
        repo_name: Name of the repository
        repo_url: URL of the repository
        callback_handler: FormattedOutputHandler instance for token tracking
    """
    print(f"\n{'='*70}")
    print(f"Analyzing Repository: {repo_name}")
    print('='*70)

    # Define analysis queries using discovery-based approach with relative paths
    queries = [
        "Analyze the repository. First show me the directory tree structure (depth 2), then identify what type of project this is by finding and examining configuration files.",

        "Based on what you discovered in the previous step, find all build-related configuration files and extract the key information like dependencies and build scripts.",

        "Based on everything you've learned so far, read the README file and extract installation/build instructions. Also search for any 'install' or 'build' commands mentioned in configuration files or scripts.",

        "Now create a comprehensive step-by-step build instruction document that includes: 1) Project type and language, 2) Prerequisites, 3) Installation commands, 4) Build commands, 5) How to run/test. Use all the information you've gathered in previous steps."
    ]

    # Initialize conversation history to maintain context across queries
    chat_history = []
    final_instructions = None
    total_tokens = {"input": 0, "output": 0, "total": 0}
    tool_usage = {}  # Track how many times each tool is used
    start_time = time.time()  # Track analysis duration

    for i, query in enumerate(queries, 1):
        print(f"\n{'-'*70}")
        print(f"Analysis Step {i}/{len(queries)}")
        print(f"{'-'*70}")
        print(f"Query: {query}\n")

        try:
            # Format chat history as readable text
            formatted_history = ""
            if chat_history:
                formatted_history = "\n".join([
                    f"Previous Query: {msg['content']}" if msg['role'] == 'user'
                    else f"Previous Answer: {msg['content'][:500]}..." if len(msg['content']) > 500
                    else f"Previous Answer: {msg['content']}"
                    for msg in chat_history
                ])

            # Invoke agent with accumulated chat history for context continuity
            result = agent.invoke({
                "input": query,
                "chat_history": formatted_history or "No previous context."
            })

            output = result['output']
            print(f"\n[RESULT]\n{output}\n")

            # Track tool usage if intermediate steps are available
            if 'intermediate_steps' in result:
                for action, _ in result['intermediate_steps']:
                    tool_name = action.tool
                    tool_usage[tool_name] = tool_usage.get(tool_name, 0) + 1

            # Track token usage if available in result - try multiple possible keys
            usage_found = False

            # Try different possible locations for usage data
            for key in ['usage_metadata', 'usage', 'token_usage', 'llm_output']:
                if key in result and result[key]:
                    usage = result[key]
                    if isinstance(usage, dict):
                        # Try different token key names
                        input_tokens = usage.get('input_tokens') or usage.get('prompt_tokens') or usage.get('total_input_tokens', 0)
                        output_tokens = usage.get('output_tokens') or usage.get('completion_tokens') or usage.get('total_output_tokens', 0)
                        total = usage.get('total_tokens', input_tokens + output_tokens)

                        if input_tokens or output_tokens:
                            total_tokens["input"] += input_tokens
                            total_tokens["output"] += output_tokens
                            total_tokens["total"] += total
                            usage_found = True
                            break

            # Debug: print available keys on first iteration if no usage found
            if i == 1 and not usage_found:
                print(f"[DEBUG] Result keys available: {list(result.keys())}")

            # Save the final step output (build instructions)
            if i == len(queries):
                final_instructions = output

            # Add this interaction to chat history for next query
            chat_history.extend([
                {"role": "user", "content": query},
                {"role": "assistant", "content": output}
            ])

        except Exception as e:
            print(f"\n[ERROR] {e}\n")

    # Calculate duration
    end_time = time.time()
    duration_seconds = end_time - start_time

    # Print summary to console (for immediate feedback)
    print(f"\n{'='*70}")
    print("Analysis Summary")
    print('='*70)
    
    duration_minutes = duration_seconds / 60
    if duration_minutes >= 1:
        print(f"Duration: {int(duration_minutes)} min {int(duration_seconds % 60)} sec")
    else:
        print(f"Duration: {duration_seconds:.2f} seconds")
    
    if tool_usage:
        total_tool_calls = sum(tool_usage.values())
        print(f"Tool calls: {total_tool_calls} (across {len(tool_usage)} unique tools)")
    
    if callback_handler and callback_handler.token_usage["total"] > 0:
        usage = callback_handler.token_usage
        print(f"Tokens: {usage['total']:,} (input: {usage['input']:,}, output: {usage['output']:,})")
    elif total_tokens["total"] > 0:
        print(f"Tokens: {total_tokens['total']:,} (input: {total_tokens['input']:,}, output: {total_tokens['output']:,})")
    
    print('='*70)

    # Save all reports and metrics to structured folder
    report_dir = save_analysis_reports(
        repo_name=repo_name,
        repo_url=repo_url,
        repo_path=repo_path,
        final_instructions=final_instructions,
        tool_usage=tool_usage,
        total_tokens=total_tokens,
        duration_seconds=duration_seconds,
        callback_handler=callback_handler
    )
    
    return report_dir


def main():
    """Main function to run repository analysis workflow."""
    print("="*70)
    print("Planner Agent - Repository Analysis Workflow")
    print("="*70)

    # Check if repository URL is provided
    if len(sys.argv) < 2:
        print("\nUsage: python run_agent.py <github_repo_url>")
        print("\nExample:")
        print("  python run_agent.py https://github.com/psf/requests")
        print("  python run_agent.py https://github.com/microsoft/playwright")
        sys.exit(1)

    repo_url = sys.argv[1]

    # Validate GitHub URL
    if "github.com" not in repo_url:
        print(f"\n[ERROR] Invalid GitHub URL: {repo_url}")
        print("Please provide a valid GitHub repository URL")
        sys.exit(1)

    try:
        # Step 1: Clone the repository
        print("\n" + "="*70)
        print("Step 1: Cloning Repository")
        print("="*70)
        repo_path = clone_repository(repo_url)
        repo_name = os.path.basename(repo_path)

        # Step 2: Initialize the agent
        print("\n" + "="*70)
        print("Step 2: Initializing Agent")
        print("="*70)
        agent, callback_handler = create_planner_agent(max_iterations=25, verbose=True, repository_path=repo_path)
        print("\n[OK] Agent initialized successfully!")

        # Step 3: Analyze the repository
        print("\n" + "="*70)
        print("Step 3: Running Analysis")
        print("="*70)
        report_dir = analyze_repository(agent, repo_path, repo_name, repo_url, callback_handler)

        # Summary
        print("\n" + "="*70)
        print("Analysis Complete!")
        print("="*70)
        print(f"\n[OK] Repository: {repo_name}")
        print(f"[OK] Repository Path: {repo_path}")
        print(f"[OK] Reports Saved: {report_dir}")
        print(f"\nAll analysis reports and metrics have been saved to:")
        print(f"  {report_dir.absolute()}")
        print(f"\nYou can now manually explore the repository at: {repo_path}")
        print("="*70)

    except KeyboardInterrupt:
        print("\n\n[WARNING] Analysis interrupted by user")
        sys.exit(0)
    except Exception as e:
        print(f"\n[ERROR] {e}")
        print("\nPlease ensure:")
        print("1. Git is installed and accessible")
        print("2. You have a .env file with AZURE_OPENAI_* variables")
        print("3. Your Azure OpenAI API key is valid")
        print("4. You have internet connectivity")
        sys.exit(1)


if __name__ == "__main__":
    main()
